@startuml
autonumber

title Receiving a referral

box "MUMC"
    actor "Referring care provider" as mp
    participant "EPD" as me
    participant "Firely Server" as mf
    participant "Referral" as mr
    participant "Nuts node" as mn
end box

box "HINQ"
    participant "IOP Nuts node" as hn
    participant "IOP FHIR interface" as hf
    participant "IOP audit serivce" as ha
end box

box "Zuyderland"
    participant "Firely Server" as zf
    participant "Firely Auth" as za
    participant "ETL" as zt
    participant "EPD" as ze
    actor "Care provider" as zp
end box

note over mr: Nuts auth flow
mp->me: Start referral flow
me->mr: Redirect to referral application
mr->mn: Search Nuts network for\norganizations supporting\nthe service
mn->mr: Available organizations
mr->mp: Present available organizations
mp->mr: Select Zuyderland
mr->mp: Display data available for referral
mp->mr: Select data to be sent
mr->mn: Issue workflow Task AuthorizationCredential that grants\naccess to workflow Task
mr->mn: Issue BGZ AuthorizationCredential that grants\naccess to referral data.
mn<-->hn: Sync new AuthorizationCredentials
mr->mn: Look up Zuyderland notification and token endpoints
mn->mr: Zuyderland notification and token endpoints
mr->mn: Get access token without\nany authorization credentials
mn->mr: Access token
mr->hf: Send Task to notification endpoint (""POST Task"")
hf->hf: Validate access token
hf->hf: Validate notification Task
note right of hf
**To check**
- ""owner.identifier"" matches token authorizer and supports bgz-receiver service (so is Zuyderland)
- ""requester.onBehalfOf.identifier"" matches token requester and supports bgz-sender service
- ""requester.agent.identifier"" matches the bgz-sender service endpoint in the requester organization's DID document
- ""input:workflow-task"" is either not set or ""true""
end note
hf->hf: Get necessary info from notifcation Task
note right of hf
**To extract**
- ""input.authorization-base"", the ID of the AuthorizationCredential to use to fetch the workflow Task
- ""requester.onBehalfOf.identifier"", the DID of the sending organization
- ""input:read-available-resources"", relative path to the workflow Task (e.g. ""Task/123"")
end note
hf->hn: Get workflow Task AuthorizationCredential\nby ID from ""Task.input.authorization-base""
hn->hf: Workflow Task AuthorizationCredential
hf->hf: Validate AuthorizationCredential exists and is valid
hf->hn: Get BGZ sender service from DID document of organization\n with DID ""Task.requester.onBehalfOf.identifier""
hn->hf: BGZ sender token and FHIR endpoints
hf->hn: Request access token with AuthorizationCredential
hn->hf: Access token
hf->hf: Get workflow Task id ""X""\nfrom notification task
hf->mf: Get workflow Task from BGZ sender service FHIR endpoint (""GET Task/X"")
note over mf: Nuts plugin
mf->hf: ""Task/X""
hf->hf: Get Patient ID ""Y"" from Task resource
hf->mf: ""GET Patient/Y""
note over mf: Nuts plugin
mf->hf: ""Patient/Y""
note over hf:**TO DO**\nSoF backend\nservices flow
note over hf:**To decide**:\nlevel of access needed\ndepending on whether or \nnot always launched from \nEHR context
group SMART Backend Services
    hf->zf **: Obtain .well-known/smart-configuration.json\nOR CapabilityStatement
    zf->hf: authorization_endpoint, token_endpoint
    hf->hf: Generate and sign one-time-use\nauthentication JWT
    create za
    note over za: **Precondition**\nZuyderland IOP node is registered\nwith agreed upon signing keypair
    hf->za: Token request\nscope: system/Patient.c system/Task.c\ngrant_type: client_credentials\nclient_assertion: <jwt>
    za->hf: Access token
end group

hf->zf: POST Task & Patient
note over zf:**Consideration**\ncustom operation
zf->zf: Process\nnotification task
zf->hf: 202 Accepted or 200 OK
hf->mr: 202 Accepted
mr->mp: Show notification sent page
zf->zt: Create\nnotification message
note right of zf: subscription,\npolling consumer?
zt->ze: Notify
ze->ze: Update worklist
ze->zp: Notify

@enduml
